In [1]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [2]:
#創建 ndarray
arr1 = np.array(data1)
arr2 = np.array(data2)

In [3]:
# 數據類型
arr1.dtype

dtype('float64')

In [4]:
#各維度大小的tuple
arr2.shape

(2L, 4L)

In [5]:
np.zeros ((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [6]:
#arange是Python內置函數range的數組版
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
arr1 = np.array([1, 2, 3], dtype=np.int32)

In [8]:
arr1.dtype

dtype('int32')

In [9]:
#可以通過astype方法 轉換 dtype :
uint_arr = arr2.astype(np.uint64)

In [10]:
uint_arr.dtype

dtype('uint64')

In [11]:
arr = np.arange(10)

In [12]:
arr_slice = arr[5:8]

In [13]:
#可以直接就這樣賦值
arr_slice[:] =64

In [14]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [15]:
lst = [i for i in range(10)]

In [16]:
#lst 與 array 的 差別 (數據的複製與否 array 會影響原數據 , lst 則是複製一份)

In [17]:
lst_slice = lst[5:8]

In [18]:
lst_slice[:] = [64,64,64]

In [19]:
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
#如果你想要得到的是ndarray切片的一份副本;而非視圖，就需要進行複製操作
arr_slice = arr[5:8].copy()

In [21]:
#2維索引
arr2d = np.array([[1 , 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [22]:
# 第一種
arr2d[0][2]

3

In [23]:
# 第二種
arr2d[0,2]

3

In [24]:
arr3d = np.array([[[1 , 2, 3], [4, 5, 6]], [[7, 8, 9],[10,11,12]]])

In [25]:
print arr3d[0],"\n=============\n",arr3d[1,0]

[[1 2 3]
 [4 5 6]] 
[7 8 9]


In [26]:
#多維度切片
print arr2d[:2],"\n=============\n",arr2d[:2,1:],"\n=============\n",arr2d[:,:1]

[[1 2 3]
 [4 5 6]] 
[[2 3]
 [5 6]] 
[[1]
 [4]
 [7]]


In [27]:
names = np.array(['Bob','Joe','Will','Bob','Will', 'Joe','Joe'])

from numpy.random import *
data  = randn(7,4)
#data  = numpy.random.randn(7,4)
data

array([[-1.30748785, -0.37270551, -0.65066499,  0.5542926 ],
       [ 1.12821333,  0.58424145, -0.53239445, -1.27855379],
       [ 1.62105848,  0.16845614, -0.32288649,  0.19879591],
       [-1.20659113, -0.63896279, -0.84899027, -1.05123121],
       [-1.67572963, -0.77147273,  0.93500914,  0.12035358],
       [-0.44938056, -0.09722333, -0.32870985,  1.32619023],
       [-0.3879667 , -0.62294523, -1.35912583, -0.20099655]])

In [28]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [29]:
data[names == 'Bob'] #輸出 0 和 3 行

array([[-1.30748785, -0.37270551, -0.65066499,  0.5542926 ],
       [-1.20659113, -0.63896279, -0.84899027, -1.05123121]])

In [30]:
mask = ( names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [31]:
data[data < 0] = 0
data

array([[ 0.        ,  0.        ,  0.        ,  0.5542926 ],
       [ 1.12821333,  0.58424145,  0.        ,  0.        ],
       [ 1.62105848,  0.16845614,  0.        ,  0.19879591],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.93500914,  0.12035358],
       [ 0.        ,  0.        ,  0.        ,  1.32619023],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [32]:
#花式索引(利用數組進行索引 -> 他跟切片不一樣 會是複製數據到新數組中)
arr = np.empty((8, 4))

for i in range(8):
    arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [33]:
#以特定順序抓取 array
arr[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [34]:
arr[[ -3, -5, - 7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [63]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [64]:
#多數組索引抓取
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [65]:
#轉置
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [69]:
#矩陣內積
print np.dot(arr,arr.T) , "\n\n\n" , arr.dot(arr.T)

[[  14   38   62   86  110  134  158  182]
 [  38  126  214  302  390  478  566  654]
 [  62  214  366  518  670  822  974 1126]
 [  86  302  518  734  950 1166 1382 1598]
 [ 110  390  670  950 1230 1510 1790 2070]
 [ 134  478  822 1166 1510 1854 2198 2542]
 [ 158  566  974 1382 1790 2198 2606 3014]
 [ 182  654 1126 1598 2070 2542 3014 3486]] 


[[  14   38   62   86  110  134  158  182]
 [  38  126  214  302  390  478  566  654]
 [  62  214  366  518  670  822  974 1126]
 [  86  302  518  734  950 1166 1382 1598]
 [ 110  390  670  950 1230 1510 1790 2070]
 [ 134  478  822 1166 1510 1854 2198 2542]
 [ 158  566  974 1382 1790 2198 2606 3014]
 [ 182  654 1126 1598 2070 2542 3014 3486]]


In [39]:
points = np.arange( -5, 5, 0.01) # 1000小伺隔約等的成

In [40]:
xs, ys = np.meshgrid(points, points) #np.meshgrid函數 兩個一維數組 -> 產生2維矩陣 

In [41]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [42]:
import matplotlib.pyplot as plt

In [43]:
z = np.sqrt (xs**2 + ys**2)

In [44]:
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [45]:
%matplotlib

Using matplotlib backend: Qt4Agg


In [46]:
plt.imshow(z, cmap=plt.cm.gray) ; plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2 }$for a grid of values")

In [47]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5 ])
cond = np.array( [True, False, True, True, False] )


In [48]:
result = np.where(cond, xarr, yarr) #cond 中的值為True時，選取 xarr的值，否則就yarr中選取。

In [49]:
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [50]:
arr = np.arange(9).reshape((3, 3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
arr.mean()

4.0

In [52]:
print arr.mean(axis = 0) , arr.mean(axis = 1) 

[ 3.  4.  5.] [ 1.  4.  7.]


In [53]:
arr.cumsum(0) #所有元素的累積和

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [54]:
arr = randn(100)
(arr > 0).sum() # 正值的計數

51

In [55]:
arr = randn(5, 3)
arr

array([[-0.4715947 ,  0.44083573,  0.55282271],
       [ 1.71214273, -1.18308949,  0.62348701],
       [-0.87439538,  0.41592138,  0.38380409],
       [-0.08413537, -1.29900577, -2.38537985],
       [ 0.68551311, -1.48126762,  0.06686395]])

In [57]:
arr.sort()
arr

array([[-0.4715947 ,  0.44083573,  0.55282271],
       [-1.18308949,  0.62348701,  1.71214273],
       [-0.87439538,  0.38380409,  0.41592138],
       [-2.38537985, -1.29900577, -0.08413537],
       [-1.48126762,  0.06686395,  0.68551311]])

In [61]:
arr.sort(0) #軸的編號
arr

array([[-2.38537985, -1.29900577, -0.08413537],
       [-1.48126762,  0.06686395,  0.41592138],
       [-1.18308949,  0.38380409,  0.55282271],
       [-0.87439538,  0.44083573,  0.68551311],
       [-0.4715947 ,  0.62348701,  1.71214273]])

In [62]:
names = np.array(['Bob','Joe','Will','Bob','Will', 'Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], 
      dtype='|S4')

In [85]:
from numpy.linalg import *

In [72]:
X = randn(5, 5)
mat = X.T.dot(X)
mat

array([[ 6.03913814,  0.80345852, -0.01658178,  1.23831837, -0.16226992],
       [ 0.80345852,  2.97970999, -2.0589024 , -0.08452486,  2.87300508],
       [-0.01658178, -2.0589024 ,  1.63268136, -0.44375223, -2.13867473],
       [ 1.23831837, -0.08452486, -0.44375223,  2.77232375, -0.25562693],
       [-0.16226992,  2.87300508, -2.13867473, -0.25562693,  5.21474714]])

In [73]:
inv(mat)

array([[   4.00923013,  -19.20188616,  -26.82360474,   -6.72757715,
          -0.62688014],
       [ -19.20188616,   96.38068836,  134.40646941,   33.31125995,
           3.05841831],
       [ -26.82360474,  134.40646941,  188.99303799,   46.78397755,
           4.91888553],
       [  -6.72757715,   33.31125995,   46.78397755,   11.98163859,
           1.21260669],
       [  -0.62688014,    3.05841831,    4.91888553,    1.21260669,
           0.56403424]])

In [87]:
mat.trace() # 對角線和

18.638600383742421

In [89]:
mat.diagonal().sum()

18.638600383742421

In [91]:
samples = np.random.normal(size = (4, 4)) #隨機生成 標準常態分布 的樣本值
samples

array([[ 0.24368234, -0.50871406,  0.42435025, -0.38471666],
       [ 0.63214998, -1.51916499,  0.76870494, -0.64647402],
       [ 1.41021617,  0.77025453, -0.17978747, -0.85328964],
       [-0.19958968, -0.85858928,  1.63636295,  1.11612338]])

In [92]:
#np.random 比起 python 內置的 random module 還要快很多